### ISSUE TITLE
What does `package.metadata.component.package` do?

### ISSUE THREAD

**Issue by feelingsonice** [bytecodealliance/component-docs#166]
What does the `package.metadata.component.package` inside of `Cargo.toml` do?
```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.34.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.component]
package = "component:hello" # <---------- seems to do nothing
```
I noticed that change or removing it seems to have no effect.
